### ISSUE TITLE
移动端app的两个意见 

### ISSUE THREAD

**Issue by jackjieYYY** [joe-vettek/ClosureHelper#1]
https://github.com/closure-studio/ReadMe/issues/47

请采纳

**Comment by joe-vettek** [comment]
![(}4(LW4 _Q{SW7UY6N{1_JB](https://user-images.githubusercontent.com/82761814/223735643-0e973c79-0139-450c-933c-b615db5b1008.png)

很早之前就做啦。issue我关掉了。
